waitingroom:
  kafka:
    topic: waiting-room-joins
  processing:
    batch-size: 10
    rate-ms: 200

spring:
  kafka:
    admin:
      auto-create: true
    consumer:
      auto-offset-reset: earliest
      group-id: waiting-room-granter

server:
  port: 8080
