server:
  port: 8094

app:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5440/local_delivery
      username: local
      password: local
    # For the demo, replica can default to the primary.
    replica:
      url: jdbc:postgresql://localhost:5440/local_delivery
      username: local
      password: local

spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
