services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: local_delivery
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5433:5432"
