server:
  port: 8097

spring:
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true

app:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5470/local_delivery
      username: local
      password: local
    replica:
      url: jdbc:postgresql://localhost:5471/local_delivery
      username: local
      password: local
