services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: local_delivery
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5450:5432"
