services:
  postgres-primary:
    image: postgres:16
    environment:
      POSTGRES_DB: local_delivery
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5440:5432"
