server:
  port: 8095

app:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5450/local_delivery
      username: local
      password: local
    replica:
      url: jdbc:postgresql://localhost:5450/local_delivery
      username: local
      password: local

spring:
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
